import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import Image from "next/image";
import Tboy2 from '../../public/image/Tboy2.png';
import SwaggerUI from '../../public/image/SwaggerUI.png';
import port from '../../public/image/port.png';
import hotel from '../../public/image/hotel.png';
import {useState} from "react"



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Benjamin John Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-mono dark:text-gray-400'>developedByBen</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-xl dark:text-gray-200'/>
              </li>
              <li><a href="#" className=' bg-gradient-to-r from-cyan-500 to-teal-700 px-4 py-2 rounded ml-8 text-white'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-700 font-medium md:text-6xl'>Benjamin John</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-400'>Software Developer and designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200'>A Versatile software engineer and designer with
               a passion for creating high-quality, engaging
                and entertaining user experience. I'm intrigued
                 by design, strategy and technology.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 text-gray-600 py-3'>
            <AiFillTwitterCircle className='cursor-pointer'/>
            <AiFillLinkedin className='cursor-pointer'/>
            <AiFillGithub className='cursor-pointer'/> 
          </div>
          <div className='relative mx-auto bg-gradient-to-l from-teal-800 rounded-full
           w-80 h-80 mt-20 shadow-2xl overflow-hidden md:h-96 md:w-96 '>
            {/* <img src='./image/Tboy2.png' alt="tboy" /> */}
            <Image src={Tboy2} object-fill/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-4 dark:text-gray-400'>Service I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I create websites that are a delight for people 
              to be on. I make sure to keep <span className='text-teal-600'>websites up to date,</span>
              give data about visitors and their behavior, assist
               with <span className='text-teal-600'>online marketing strategy</span> and provide regular
                backups of the site.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I am good at <span className='text-teal-600'>creating a good relationship</span> and 
              an emotional reaction in your users that makes 
              them want to take action.
            </p>
          </div>
          <div className='lg:grid grid-cols-3 gap-10'>
          <div className='text-center shadow-xl py-10 rounded-xl my-10 dark:bg-gray-200'>
            <Image src={SwaggerUI} width={200} height={200} className='mx-auto'/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Swagger UI</h3>
            <p className=' py-2 mx-4'>Creating elegant API implementain using ASP.NET
               Core and .NET Frameworks wih suitable software Design 
               and Architectural patterns 
              </p>
              <h3 className='py-2 text-teal-600'>Tools</h3>
              <p className=' text-gray-400 py-0'>Visual Studio</p>
              <p className=' text-gray-400 py-0'>C# and .NET</p>
          </div>

          <div className='text-center shadow-lg py-10 rounded-xl my-10 dark:bg-gray-200'>
            <a href="https://jbenportfolio.netlify.app/">
            <Image src={port} width={200} height={200} className='mx-auto'/>
            </a>
            <h3 className='text-lg font-medium pt-8 pb-2'>Swagger UI</h3>
            <p className=' py-2 mx-4'>Creating Awesome  Designs that meets 
              customer's satisfaction and also viewer friendly
              </p>
              <h3 className='py-2 text-teal-600'>Tools</h3>
              <p className=' text-gray-400 py-0'>Visual Studio Code</p>
              <p className=' text-gray-400 py-0'>HTML,CSS/Tailwind</p>
          </div>

          <div className='text-center shadow-lg py-10 rounded-xl my-10 dark:bg-gray-200'>
            <Image src={hotel} width={200} height={200} className='mx-auto'/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Swagger UI</h3>
            <p className=' py-2 mx-4'>Creating Awesome  Designs that meets 
              customer's satisfaction and also viewer friendly
              </p>
              <h3 className='py-2 text-teal-600'>Tools</h3>
              <p className=' text-gray-400 py-0'>Visual Studio code</p>
              <p className=' text-gray-400 py-0'>HTML and Css</p>
              <p className=' text-gray-400 py-0'>React</p>
          </div>
          </div>
          
        </section>
        <section>
          <h3 className='text-3xl py-1 dark:text-gray-400'>Portfolio</h3>
        </section>
      </main>
    </div>
  )
}
